### ISSUE TITLE
Dotnet version

### ISSUE THREAD

**Issue by Jordanjun98** [yogyogi/ASP.NET-Core-CMS#1]
May I know what is the dotnet version are u using for the project as when i run `dotnet ef` it shows  `No executable found matching command "dotnet-ef"`

**Comment by yogyogi** [comment]
Hello @Jordanjun98,

The project is made in ASP.NET Core 2.0 and used [EF Core 2.0](https://www.yogihosting.com/category/ef-core/). 

Thank you!

**Comment by Jordanjun98** [comment]
Will that be fine if i use version 3.1.2?

**Comment by yogyogi** [comment]
I don't think so.

**Comment by Jordanjun98** [comment]
May I know do u know how to solve the `Build failed` as when i enter this command `dotnet ef database update --context AppIdentityDbContext` it shows build failed

**Comment by yogyogi** [comment]
ASP.NET Core 2.0 version is needed for this project to run.

**Comment by yogyogi** [comment]
It is now updated to ASP.NET Core 5.0 version. I have also provided links to 2 Youtube videos which explains it's installation and working procedures.
